sudo: required

language: cpp

compiler: 
    - g++

install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-5
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
    - sudo apt-get install cmake
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - sudo cp *.a /usr/lib

before_script:
    - cd /home/travis/build/DmitryGr/tp-projectcopy
    - chmod 777 run.sh

script:
    - ./run.sh
