sudo: required

before script:
    - chmod 777 run.sh

language: cpp

compiler: 
    - g++

install:
    - sudo apt-get install cmake
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make
    - cd ~

script:
    - ./run.sh
