sudo: required

language: cpp

compiler: 
    - g++

install:
    - sudo apt-get install cmake
    - sudo apt install libgtest-dev build-essential cmake
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo cmake --build . --target install

before_script:
    - cd /home/travis/build/DmitryGr/tp-projectcopy
    - chmod 777 run.sh

script:
    - ./run.sh
