sudo: required

language: cpp

compiler: 
    - g++

install:
    - sudo apt-get install cmake
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake CMakeLists.txt
    - sudo make

before script:
    - cd /home/travis
    - chmod 777 script.sh

script:
    - ./run.sh
